### ISSUE TITLE
make a small gif that shows all the options

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo-py/ir-teaching-app#3]
we could just add some text and then use it to share on twitter etc.

**Comment by lpatiny** [comment]
![2021-10-05 14 35 07](https://user-images.githubusercontent.com/1484241/136023990-887dd82e-a857-4e95-a00a-717f5bab7f35.gif)

**Comment by kjappelbaum** [comment]
https://www.icloud.com/iclouddrive/0ne2rNnnPa63YC2zzvIAjqaBg#ircalc_video

**Comment by kjappelbaum** [comment]
Good idea, or do we have a better name? If we have no better name, I can buy it.

On 6 Oct 2021, at 19:01, Luc Patiny ***@***.***> wrote:

﻿

Looks great ! Do you want to register the domain name ircalc.org ? It is not taken in fact.

**Comment by lpatiny** [comment]
For me it is ok. Just don't loose it ... I have a super bad experience with www.ecoscale.org. We published it here https://www.beilstein-journals.org/bjoc/articles/1860-5397-2-3 but the co-author didn't renew the domain name.
